defaultTest: {}
description: My eval
env: {}
evaluateOptions: {}
prompts:
  - Write a tweet about {{topic}}
  - Write a concise, funny tweet about {{topic}}
providers:
  - ollama:chat:llama3.1

scenarios: []
tests:
  - vars:
      topic: bananas
  - vars:
      topic: avocado toast
    assert:
      - type: icontains
        value: avocado
      - type: javascript
        value: 1 / (output.length + 1)
  - vars:
      topic: new york city
    assert:
      - type: llm-rubric
        value: ensure that the output is kindly and friendly
        provider: ollama:chat:llama3.1
